### ISSUE TITLE
Setting Data-type for Field without database representation

### ISSUE THREAD

**Issue by hoermillerj** [wiredviews/xperience-page-navigation-redirects#1]
Kentico: 13.0.118
XperienceCommunity.PageNavigationRedirects: 1.1.0
XperienceCommunity.PageBuilderUtilities: 1.1.0

The documentation states that I should create a new page-type field `PageInternalRedirectNodeGuid` with the Field type set to `Field without database representation` and the Data type set to `Unique identifier (GUID)`.
When selecting `Field without database representation` as a field type I am not able to set the data type and it is automatically set to `Text`.

This issue only applies to page-types that are inherited by other page-types.

Should I set the field type to something else or what would be the correct way to resolve this issue?

**Comment by seangwright** [comment]
@hoermillerj I believe this _might_ be a UI bug in Kentico Xperience 13.

If you open devtools and inspect the `<select>` element for the Data Type, you will notice it has a `disabled` attribute (if I remember correctly). You can remove that attribute and then change the Data Type. You should only need to do this when setting up the base Page Type fields, which will all be inherited to your other Page Types.

Making the Data Type modifiable has no negative effect on the Page Types or your solution, it's just a scenario that isn't correctly accounted for (from my investigations) in the UI.

Let me know if that unblocks you. If not, I can open an KX13 solution and see if I'm misremembering the steps 👍.

**Comment by hoermillerj** [comment]
@seangwright thanks, that worked.
That is a very weird UI bug 🤷‍♂️
